<?php
/**
 * TeachingClassJsonldTeachingClassDetailTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starfish Labz API
 *
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TeachingClassJsonldTeachingClassDetailTest Class Doc Comment
 *
 * @category    Class
 * @description TeachingClassJsonldTeachingClassDetail
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TeachingClassJsonldTeachingClassDetailTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TeachingClassJsonldTeachingClassDetail"
     */
    public function testTeachingClassJsonldTeachingClassDetail()
    {
    }

    /**
     * Test attribute "context"
     */
    public function testPropertyContext()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "updated"
     */
    public function testPropertyUpdated()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "grade"
     */
    public function testPropertyGrade()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "term"
     */
    public function testPropertyTerm()
    {
    }

    /**
     * Test attribute "start"
     */
    public function testPropertyStart()
    {
    }

    /**
     * Test attribute "end"
     */
    public function testPropertyEnd()
    {
    }

    /**
     * Test attribute "is_finished"
     */
    public function testPropertyIsFinished()
    {
    }

    /**
     * Test attribute "avatar"
     */
    public function testPropertyAvatar()
    {
    }

    /**
     * Test attribute "num_teachers"
     */
    public function testPropertyNumTeachers()
    {
    }

    /**
     * Test attribute "creator"
     */
    public function testPropertyCreator()
    {
    }

    /**
     * Test attribute "school"
     */
    public function testPropertySchool()
    {
    }

    /**
     * Test attribute "students"
     */
    public function testPropertyStudents()
    {
    }

    /**
     * Test attribute "teaching_class_students"
     */
    public function testPropertyTeachingClassStudents()
    {
    }

    /**
     * Test attribute "teachers"
     */
    public function testPropertyTeachers()
    {
    }

    /**
     * Test attribute "learning_skills"
     */
    public function testPropertyLearningSkills()
    {
    }

    /**
     * Test attribute "invitation_code"
     */
    public function testPropertyInvitationCode()
    {
    }
}
