/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The AnyOfTeachingClassStudentjsonldTeachingClassStudentListTeachingClass model module.
* @module model/AnyOfTeachingClassStudentjsonldTeachingClassStudentListTeachingClass
* @version 1.0.0
*/
export default class AnyOfTeachingClassStudentjsonldTeachingClassStudentListTeachingClass {
    /**
    * Constructs a new <code>AnyOfTeachingClassStudentjsonldTeachingClassStudentListTeachingClass</code>.
    * @alias module:model/AnyOfTeachingClassStudentjsonldTeachingClassStudentListTeachingClass
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>AnyOfTeachingClassStudentjsonldTeachingClassStudentListTeachingClass</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AnyOfTeachingClassStudentjsonldTeachingClassStudentListTeachingClass} obj Optional instance to populate.
    * @return {module:model/AnyOfTeachingClassStudentjsonldTeachingClassStudentListTeachingClass} The populated <code>AnyOfTeachingClassStudentjsonldTeachingClassStudentListTeachingClass</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AnyOfTeachingClassStudentjsonldTeachingClassStudentListTeachingClass();
                        
            
        }
        return obj;
    }





}
