/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The EmailSubscriptionEmailSubscriptionWrite model module.
* @module model/EmailSubscriptionEmailSubscriptionWrite
* @version 1.0.0
*/
export default class EmailSubscriptionEmailSubscriptionWrite {
    /**
    * Constructs a new <code>EmailSubscriptionEmailSubscriptionWrite</code>.
    * @alias module:model/EmailSubscriptionEmailSubscriptionWrite
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>EmailSubscriptionEmailSubscriptionWrite</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EmailSubscriptionEmailSubscriptionWrite} obj Optional instance to populate.
    * @return {module:model/EmailSubscriptionEmailSubscriptionWrite} The populated <code>EmailSubscriptionEmailSubscriptionWrite</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmailSubscriptionEmailSubscriptionWrite();
                        
            
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} user
    */
    'user' = undefined;




}
