/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The LearningSkillLearningSkillWrite model module.
* @module model/LearningSkillLearningSkillWrite
* @version 1.0.0
*/
export default class LearningSkillLearningSkillWrite {
    /**
    * Constructs a new <code>LearningSkillLearningSkillWrite</code>.
    * @alias module:model/LearningSkillLearningSkillWrite
    * @class
    * @param name {String} 
    */

    constructor(name) {
        
        
        this['name'] = name;
        
    }

    /**
    * Constructs a <code>LearningSkillLearningSkillWrite</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/LearningSkillLearningSkillWrite} obj Optional instance to populate.
    * @return {module:model/LearningSkillLearningSkillWrite} The populated <code>LearningSkillLearningSkillWrite</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LearningSkillLearningSkillWrite();
                        
            
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    'name' = undefined;
    /**
    * @member {String} avatar
    */
    'avatar' = undefined;




}
