/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The MediaMediaWrite model module.
* @module model/MediaMediaWrite
* @version 1.0.0
*/
export default class MediaMediaWrite {
    /**
    * Constructs a new <code>MediaMediaWrite</code>.
    * @alias module:model/MediaMediaWrite
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MediaMediaWrite</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MediaMediaWrite} obj Optional instance to populate.
    * @return {module:model/MediaMediaWrite} The populated <code>MediaMediaWrite</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MediaMediaWrite();
                        
            
            if (data.hasOwnProperty('mediaType')) {
                obj['mediaType'] = ApiClient.convertToType(data['mediaType'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} mediaType
    */
    'mediaType' = undefined;




}
