/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The NotificationNotificationWrite model module.
* @module model/NotificationNotificationWrite
* @version 1.0.0
*/
export default class NotificationNotificationWrite {
    /**
    * Constructs a new <code>NotificationNotificationWrite</code>.
    * Class Notification
    * @alias module:model/NotificationNotificationWrite
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>NotificationNotificationWrite</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NotificationNotificationWrite} obj Optional instance to populate.
    * @return {module:model/NotificationNotificationWrite} The populated <code>NotificationNotificationWrite</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NotificationNotificationWrite();
                        
            
            if (data.hasOwnProperty('isRead')) {
                obj['isRead'] = ApiClient.convertToType(data['isRead'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} isRead
    */
    'isRead' = undefined;




}
