/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserjsonldRatingList from './UserjsonldRatingList';

/**
* The RatingjsonldRatingList model module.
* @module model/RatingjsonldRatingList
* @version 1.0.0
*/
export default class RatingjsonldRatingList {
    /**
    * Constructs a new <code>RatingjsonldRatingList</code>.
    * @alias module:model/RatingjsonldRatingList
    * @class
    * @param _date {Date} 
    * @param points {Number} 
    */

    constructor(_date, points) {
        
        
        this['date'] = _date;
        this['points'] = points;
        
    }

    /**
    * Constructs a <code>RatingjsonldRatingList</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RatingjsonldRatingList} obj Optional instance to populate.
    * @return {module:model/RatingjsonldRatingList} The populated <code>RatingjsonldRatingList</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RatingjsonldRatingList();
                        
            
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Date');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('points')) {
                obj['points'] = ApiClient.convertToType(data['points'], 'Number');
            }
            if (data.hasOwnProperty('teachingClass')) {
                obj['teachingClass'] = ApiClient.convertToType(data['teachingClass'], 'String');
            }
            if (data.hasOwnProperty('learningSkill')) {
                obj['learningSkill'] = ApiClient.convertToType(data['learningSkill'], 'String');
            }
            if (data.hasOwnProperty('creator')) {
                obj['creator'] = UserjsonldRatingList.constructFromObject(data['creator']);
            }
        }
        return obj;
    }

    /**
    * @member {String} @id
    */
    '@id' = undefined;
    /**
    * @member {String} @type
    */
    '@type' = undefined;
    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {Date} created
    */
    'created' = undefined;
    /**
    * @member {Date} updated
    */
    'updated' = undefined;
    /**
    * @member {Date} date
    */
    'date' = undefined;
    /**
    * @member {String} description
    */
    'description' = undefined;
    /**
    * @member {Number} points
    */
    'points' = undefined;
    /**
    * @member {String} teachingClass
    */
    'teachingClass' = undefined;
    /**
    * @member {String} learningSkill
    */
    'learningSkill' = undefined;
    /**
    * @member {module:model/UserjsonldRatingList} creator
    */
    'creator' = undefined;




}
