/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The RatingMediajsonldRatingMediaWrite model module.
* @module model/RatingMediajsonldRatingMediaWrite
* @version 1.0.0
*/
export default class RatingMediajsonldRatingMediaWrite {
    /**
    * Constructs a new <code>RatingMediajsonldRatingMediaWrite</code>.
    * @alias module:model/RatingMediajsonldRatingMediaWrite
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>RatingMediajsonldRatingMediaWrite</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RatingMediajsonldRatingMediaWrite} obj Optional instance to populate.
    * @return {module:model/RatingMediajsonldRatingMediaWrite} The populated <code>RatingMediajsonldRatingMediaWrite</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RatingMediajsonldRatingMediaWrite();
                        
            
            if (data.hasOwnProperty('@context')) {
                obj['@context'] = ApiClient.convertToType(data['@context'], 'String');
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'String');
            }
            if (data.hasOwnProperty('media')) {
                obj['media'] = ApiClient.convertToType(data['media'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} @context
    */
    '@context' = undefined;
    /**
    * @member {String} @id
    */
    '@id' = undefined;
    /**
    * @member {String} @type
    */
    '@type' = undefined;
    /**
    * @member {String} rating
    */
    'rating' = undefined;
    /**
    * @member {String} media
    */
    'media' = undefined;




}
