/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TeachingClassStudentTeachingClassStudentWrite model module.
* @module model/TeachingClassStudentTeachingClassStudentWrite
* @version 1.0.0
*/
export default class TeachingClassStudentTeachingClassStudentWrite {
    /**
    * Constructs a new <code>TeachingClassStudentTeachingClassStudentWrite</code>.
    * @alias module:model/TeachingClassStudentTeachingClassStudentWrite
    * @class
    * @param code {String} 
    */

    constructor(code) {
        
        
        this['code'] = code;
        
    }

    /**
    * Constructs a <code>TeachingClassStudentTeachingClassStudentWrite</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TeachingClassStudentTeachingClassStudentWrite} obj Optional instance to populate.
    * @return {module:model/TeachingClassStudentTeachingClassStudentWrite} The populated <code>TeachingClassStudentTeachingClassStudentWrite</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeachingClassStudentTeachingClassStudentWrite();
                        
            
            if (data.hasOwnProperty('teachingClass')) {
                obj['teachingClass'] = ApiClient.convertToType(data['teachingClass'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} teachingClass
    */
    'teachingClass' = undefined;
    /**
    * @member {String} firstName
    */
    'firstName' = undefined;
    /**
    * @member {String} lastName
    */
    'lastName' = undefined;
    /**
    * @member {String} avatar
    */
    'avatar' = undefined;
    /**
    * @member {String} code
    */
    'code' = undefined;




}
