/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TeachingClassLearningSkillTeachingClassLearningSkillDetail model module.
* @module model/TeachingClassLearningSkillTeachingClassLearningSkillDetail
* @version 1.0.0
*/
export default class TeachingClassLearningSkillTeachingClassLearningSkillDetail {
    /**
    * Constructs a new <code>TeachingClassLearningSkillTeachingClassLearningSkillDetail</code>.
    * @alias module:model/TeachingClassLearningSkillTeachingClassLearningSkillDetail
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>TeachingClassLearningSkillTeachingClassLearningSkillDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/TeachingClassLearningSkillTeachingClassLearningSkillDetail} obj Optional instance to populate.
    * @return {module:model/TeachingClassLearningSkillTeachingClassLearningSkillDetail} The populated <code>TeachingClassLearningSkillTeachingClassLearningSkillDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TeachingClassLearningSkillTeachingClassLearningSkillDetail();
                        
            
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Date');
            }
            if (data.hasOwnProperty('teachingClass')) {
                obj['teachingClass'] = ApiClient.convertToType(data['teachingClass'], 'String');
            }
            if (data.hasOwnProperty('learningSkill')) {
                obj['learningSkill'] = ApiClient.convertToType(data['learningSkill'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {Date} created
    */
    'created' = undefined;
    /**
    * @member {Date} updated
    */
    'updated' = undefined;
    /**
    * @member {String} teachingClass
    */
    'teachingClass' = undefined;
    /**
    * @member {String} learningSkill
    */
    'learningSkill' = undefined;




}
