/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ModelObject from './ModelObject';

/**
* The UserjsonldUserDetail model module.
* @module model/UserjsonldUserDetail
* @version 1.0.0
*/
export default class UserjsonldUserDetail {
    /**
    * Constructs a new <code>UserjsonldUserDetail</code>.
    * Class User
    * @alias module:model/UserjsonldUserDetail
    * @class
    * @param username {String} 
    */

    constructor(username) {
        
        
        this['username'] = username;
        
    }

    /**
    * Constructs a <code>UserjsonldUserDetail</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserjsonldUserDetail} obj Optional instance to populate.
    * @return {module:model/UserjsonldUserDetail} The populated <code>UserjsonldUserDetail</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserjsonldUserDetail();
                        
            
            if (data.hasOwnProperty('@context')) {
                obj['@context'] = ApiClient.convertToType(data['@context'], 'String');
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
            if (data.hasOwnProperty('updated')) {
                obj['updated'] = ApiClient.convertToType(data['updated'], 'Date');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('preferredLanguage')) {
                obj['preferredLanguage'] = ApiClient.convertToType(data['preferredLanguage'], 'String');
            }
            if (data.hasOwnProperty('avatar')) {
                obj['avatar'] = ApiClient.convertToType(data['avatar'], ModelObject);
            }
            if (data.hasOwnProperty('school')) {
                obj['school'] = ApiClient.convertToType(data['school'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('privacyPolicyLastAgreed')) {
                obj['privacyPolicyLastAgreed'] = ApiClient.convertToType(data['privacyPolicyLastAgreed'], 'Date');
            }
            if (data.hasOwnProperty('occupation')) {
                obj['occupation'] = ApiClient.convertToType(data['occupation'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} @context
    */
    '@context' = undefined;
    /**
    * @member {String} @id
    */
    '@id' = undefined;
    /**
    * @member {String} @type
    */
    '@type' = undefined;
    /**
    * @member {Number} id
    */
    'id' = undefined;
    /**
    * @member {Date} created
    */
    'created' = undefined;
    /**
    * @member {Date} updated
    */
    'updated' = undefined;
    /**
    * @member {String} username
    */
    'username' = undefined;
    /**
    * @member {String} email
    */
    'email' = undefined;
    /**
    * @member {String} firstName
    */
    'firstName' = undefined;
    /**
    * @member {String} lastName
    */
    'lastName' = undefined;
    /**
    * @member {String} preferredLanguage
    */
    'preferredLanguage' = undefined;
    /**
    * @member {module:model/ModelObject} avatar
    */
    'avatar' = undefined;
    /**
    * @member {String} school
    */
    'school' = undefined;
    /**
    * @member {String} phone
    */
    'phone' = undefined;
    /**
    * @member {Date} privacyPolicyLastAgreed
    */
    'privacyPolicyLastAgreed' = undefined;
    /**
    * @member {String} occupation
    */
    'occupation' = undefined;




}
