/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfishLabzApi);
  }
}(this, function(expect, StarfishLabzApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfishLabzApi.StudentProfileUserInvitationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StudentProfileUserInvitationApi', function() {
    describe('apiAuthV1StudentProfileUserInvitationPost', function() {
      it('should call apiAuthV1StudentProfileUserInvitationPost successfully', function(done) {
        //uncomment below and update the code to test apiAuthV1StudentProfileUserInvitationPost
        //instance.apiAuthV1StudentProfileUserInvitationPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiAuthV1StudentProfileUserInvitationStudentProfileUserInvitationIdAcceptPost', function() {
      it('should call apiAuthV1StudentProfileUserInvitationStudentProfileUserInvitationIdAcceptPost successfully', function(done) {
        //uncomment below and update the code to test apiAuthV1StudentProfileUserInvitationStudentProfileUserInvitationIdAcceptPost
        //instance.apiAuthV1StudentProfileUserInvitationStudentProfileUserInvitationIdAcceptPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('apiAuthV1StudentProfileUserInvitationStudentProfileUserInvitationIdRejectPost', function() {
      it('should call apiAuthV1StudentProfileUserInvitationStudentProfileUserInvitationIdRejectPost successfully', function(done) {
        //uncomment below and update the code to test apiAuthV1StudentProfileUserInvitationStudentProfileUserInvitationIdRejectPost
        //instance.apiAuthV1StudentProfileUserInvitationStudentProfileUserInvitationIdRejectPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStudentProfileUserInvitationCollection', function() {
      it('should call getStudentProfileUserInvitationCollection successfully', function(done) {
        //uncomment below and update the code to test getStudentProfileUserInvitationCollection
        //instance.getStudentProfileUserInvitationCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStudentProfileUserInvitationItem', function() {
      it('should call getStudentProfileUserInvitationItem successfully', function(done) {
        //uncomment below and update the code to test getStudentProfileUserInvitationItem
        //instance.getStudentProfileUserInvitationItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
