/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.StarfishLabzApi);
  }
}(this, function(expect, StarfishLabzApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new StarfishLabzApi.TeachingClassLearningSkillApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TeachingClassLearningSkillApi', function() {
    describe('deleteTeachingClassLearningSkillItem', function() {
      it('should call deleteTeachingClassLearningSkillItem successfully', function(done) {
        //uncomment below and update the code to test deleteTeachingClassLearningSkillItem
        //instance.deleteTeachingClassLearningSkillItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTeachingClassLearningSkillCollection', function() {
      it('should call getTeachingClassLearningSkillCollection successfully', function(done) {
        //uncomment below and update the code to test getTeachingClassLearningSkillCollection
        //instance.getTeachingClassLearningSkillCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getTeachingClassLearningSkillItem', function() {
      it('should call getTeachingClassLearningSkillItem successfully', function(done) {
        //uncomment below and update the code to test getTeachingClassLearningSkillItem
        //instance.getTeachingClassLearningSkillItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postTeachingClassLearningSkillCollection', function() {
      it('should call postTeachingClassLearningSkillCollection successfully', function(done) {
        //uncomment below and update the code to test postTeachingClassLearningSkillCollection
        //instance.postTeachingClassLearningSkillCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
