/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";

/**
* PrivacyPolicy service.
* @module api/PrivacyPolicyApi
* @version 1.0.0
*/
export default class PrivacyPolicyApi {

    /**
    * Constructs a new PrivacyPolicyApi. 
    * @alias module:api/PrivacyPolicyApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiAuthV1PrivacyPolicyAcceptPost operation.
     * @callback module:api/PrivacyPolicyApi~apiAuthV1PrivacyPolicyAcceptPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Accept privacy policy
     * @param {module:api/PrivacyPolicyApi~apiAuthV1PrivacyPolicyAcceptPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiAuthV1PrivacyPolicyAcceptPost(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/auth/v1/privacy-policy/accept', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
