/**
 * Starfish Labz API
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient";
import InlineResponse20017 from '../model/InlineResponse20017';
import TeachingClassTeacherInvitationjsonldTeachingClassTeacherInvitationDetail from '../model/TeachingClassTeacherInvitationjsonldTeachingClassTeacherInvitationDetail';

/**
* TeachingClassTeacherInvitation service.
* @module api/TeachingClassTeacherInvitationApi
* @version 1.0.0
*/
export default class TeachingClassTeacherInvitationApi {

    /**
    * Constructs a new TeachingClassTeacherInvitationApi. 
    * @alias module:api/TeachingClassTeacherInvitationApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the apiAuthV1TeachingClassTeacherInvitationPost operation.
     * @callback module:api/TeachingClassTeacherInvitationApi~apiAuthV1TeachingClassTeacherInvitationPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Allows user to send an invitation to a teaching class with a given invitation code.
     * @param {module:api/TeachingClassTeacherInvitationApi~apiAuthV1TeachingClassTeacherInvitationPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiAuthV1TeachingClassTeacherInvitationPost(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/auth/v1/teaching-class-teacher-invitation', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiAuthV1TeachingClassTeacherInvitationTeachingClassTeacherInvitationIdAcceptPost operation.
     * @callback module:api/TeachingClassTeacherInvitationApi~apiAuthV1TeachingClassTeacherInvitationTeachingClassTeacherInvitationIdAcceptPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Accept Teaching Class Teacher Invitation
     * @param {module:api/TeachingClassTeacherInvitationApi~apiAuthV1TeachingClassTeacherInvitationTeachingClassTeacherInvitationIdAcceptPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiAuthV1TeachingClassTeacherInvitationTeachingClassTeacherInvitationIdAcceptPost(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/auth/v1/teaching-class-teacher-invitation/{teachingClassTeacherInvitationId}/accept', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the apiAuthV1TeachingClassTeacherInvitationTeachingClassTeacherInvitationIdRejectPost operation.
     * @callback module:api/TeachingClassTeacherInvitationApi~apiAuthV1TeachingClassTeacherInvitationTeachingClassTeacherInvitationIdRejectPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Reject Teaching Class Teacher Invitation
     * @param {module:api/TeachingClassTeacherInvitationApi~apiAuthV1TeachingClassTeacherInvitationTeachingClassTeacherInvitationIdRejectPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    apiAuthV1TeachingClassTeacherInvitationTeachingClassTeacherInvitationIdRejectPost(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/auth/v1/teaching-class-teacher-invitation/{teachingClassTeacherInvitationId}/reject', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getTeachingClassTeacherInvitationCollection operation.
     * @callback module:api/TeachingClassTeacherInvitationApi~getTeachingClassTeacherInvitationCollectionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20017} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves the collection of TeachingClassTeacherInvitation resources.
     * @param {Object} opts Optional parameters
     * @param {module:api/TeachingClassTeacherInvitationApi~getTeachingClassTeacherInvitationCollectionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20017}
     */
    getTeachingClassTeacherInvitationCollection(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'teaching_class.id': opts['teachingClassId'],
        'teaching_class.id[]': this.apiClient.buildCollectionParam(opts['teachingClassId'], 'multi'),
        'page': opts['page'],
        'itemsPerPage': opts['itemsPerPage']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/ld+json', 'application/json', 'text/html'];
      let returnType = InlineResponse20017;

      return this.apiClient.callApi(
        '/api/auth/v1/teaching-class-teacher-invitations', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getTeachingClassTeacherInvitationItem operation.
     * @callback module:api/TeachingClassTeacherInvitationApi~getTeachingClassTeacherInvitationItemCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TeachingClassTeacherInvitationjsonldTeachingClassTeacherInvitationDetail} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves a TeachingClassTeacherInvitation resource.
     * @param {module:api/TeachingClassTeacherInvitationApi~getTeachingClassTeacherInvitationItemCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TeachingClassTeacherInvitationjsonldTeachingClassTeacherInvitationDetail}
     */
    getTeachingClassTeacherInvitationItem(id, callback) {
      let postBody = null;

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiKey'];
      let contentTypes = [];
      let accepts = ['application/ld+json', 'application/json', 'text/html'];
      let returnType = TeachingClassTeacherInvitationjsonldTeachingClassTeacherInvitationDetail;

      return this.apiClient.callApi(
        '/api/auth/v1/teaching-class-teacher-invitation/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}
