<?php
/**
 * TeachingClassStudentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starfish Labz API
 *
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TeachingClassStudentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TeachingClassStudentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for apiAuthV1TeachingClassStudentCopyPost
     *
     * Allows user to copy existing students to a specified teaching class..
     *
     */
    public function testApiAuthV1TeachingClassStudentCopyPost()
    {
    }

    /**
     * Test case for deleteTeachingClassStudentItem
     *
     * Removes the TeachingClassStudent resource..
     *
     */
    public function testDeleteTeachingClassStudentItem()
    {
    }

    /**
     * Test case for getTeachingClassStudentCollection
     *
     * Retrieves the collection of TeachingClassStudent resources..
     *
     */
    public function testGetTeachingClassStudentCollection()
    {
    }

    /**
     * Test case for getTeachingClassStudentItem
     *
     * Retrieves a TeachingClassStudent resource..
     *
     */
    public function testGetTeachingClassStudentItem()
    {
    }

    /**
     * Test case for patchTeachingClassStudentItem
     *
     * Updates the TeachingClassStudent resource..
     *
     */
    public function testPatchTeachingClassStudentItem()
    {
    }

    /**
     * Test case for postTeachingClassStudentCollection
     *
     * Creates a TeachingClassStudent resource..
     *
     */
    public function testPostTeachingClassStudentCollection()
    {
    }

    /**
     * Test case for putTeachingClassStudentItem
     *
     * Replaces the TeachingClassStudent resource..
     *
     */
    public function testPutTeachingClassStudentItem()
    {
    }
}
