<?php
/**
 * TeachingClassApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Starfish Labz API
 *
 * This page provides documentation on how to use the Starfish Labz API. Please contact us should you wish to access the API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TeachingClassApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TeachingClassApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getLearningSkillsTeachingClassItem
     *
     * Retrieves a TeachingClass resource..
     *
     */
    public function testGetLearningSkillsTeachingClassItem()
    {
    }

    /**
     * Test case for getTeachingClassCollection
     *
     * Retrieves the collection of TeachingClass resources..
     *
     */
    public function testGetTeachingClassCollection()
    {
    }

    /**
     * Test case for getTeachingClassItem
     *
     * Retrieves a TeachingClass resource..
     *
     */
    public function testGetTeachingClassItem()
    {
    }

    /**
     * Test case for patchTeachingClassItem
     *
     * Updates the TeachingClass resource..
     *
     */
    public function testPatchTeachingClassItem()
    {
    }

    /**
     * Test case for postTeachingClassCollection
     *
     * Creates a TeachingClass resource..
     *
     */
    public function testPostTeachingClassCollection()
    {
    }

    /**
     * Test case for putTeachingClassItem
     *
     * Replaces the TeachingClass resource..
     *
     */
    public function testPutTeachingClassItem()
    {
    }
}
